"""Initial migration

Revision ID: 265fbbcc63d5
Revises:
Create Date: 2025-11-22 00:49:17.150994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "265fbbcc63d5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "one_time_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(start_date < end_date) OR (start_date = end_date AND start_time < end_time)",
            name="one_time_valid_datetime_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_one_time_sessions_id"), "one_time_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_one_time_sessions_start_date"), "one_time_sessions", ["start_date"], unique=False)
    op.create_table(
        "recurring_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recurrence_pattern", sa.String(length=20), nullable=False),
        sa.Column("recurrence_value", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "recurrence_pattern != 'weekly' OR (recurrence_value >= 0 AND recurrence_value <= 6)",
            name="recurring_valid_weekly_day",
        ),
        sa.CheckConstraint(
            "(start_date < end_date) OR (start_date = end_date AND start_time < end_time)",
            name="recurring_valid_datetime_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recurring_sessions_id"), "recurring_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_recurring_sessions_start_date"), "recurring_sessions", ["start_date"], unique=False)
    op.create_table(
        "recurring_overrides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recurring_session_id", sa.Integer(), nullable=False),
        sa.Column("occurrence_date", sa.Date(), nullable=False),
        sa.Column("override_type", sa.String(length=20), nullable=False),
        sa.Column("modified_title", sa.String(length=255), nullable=True),
        sa.Column("modified_notes", sa.Text(), nullable=True),
        sa.Column("modified_start_time", sa.Time(), nullable=True),
        sa.Column("modified_end_time", sa.Time(), nullable=True),
        sa.Column("modified_end_date", sa.Date(), nullable=True, comment="Only if session becomes overnight"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "override_type != 'cancelled' OR (modified_title IS NULL AND modified_notes IS NULL AND modified_start_time IS NULL AND modified_end_time IS NULL AND modified_end_date IS NULL)",
            name="ck_cancelled_no_modifications",
        ),
        sa.CheckConstraint(
            "override_type != 'modified' OR (modified_title IS NOT NULL OR modified_notes IS NOT NULL OR modified_start_time IS NOT NULL OR modified_end_time IS NOT NULL OR modified_end_date IS NOT NULL)",
            name="ck_modified_has_changes",
        ),
        sa.CheckConstraint("override_type IN ('cancelled', 'modified')", name="ck_valid_override_type"),
        sa.CheckConstraint(
            "modified_start_time IS NULL OR modified_end_time IS NULL OR modified_end_date IS NOT NULL OR modified_end_time > modified_start_time",
            name="ck_valid_time_range",
        ),
        sa.ForeignKeyConstraint(["recurring_session_id"], ["recurring_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recurring_session_id", "occurrence_date", name="uq_override_per_occurrence"),
    )
    op.create_index(op.f("ix_recurring_overrides_id"), "recurring_overrides", ["id"], unique=False)
    op.create_index(
        op.f("ix_recurring_overrides_occurrence_date"), "recurring_overrides", ["occurrence_date"], unique=False
    )
    op.create_index(
        op.f("ix_recurring_overrides_override_type"), "recurring_overrides", ["override_type"], unique=False
    )
    op.create_index(
        op.f("ix_recurring_overrides_recurring_session_id"),
        "recurring_overrides",
        ["recurring_session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recurring_overrides_recurring_session_id"), table_name="recurring_overrides")
    op.drop_index(op.f("ix_recurring_overrides_override_type"), table_name="recurring_overrides")
    op.drop_index(op.f("ix_recurring_overrides_occurrence_date"), table_name="recurring_overrides")
    op.drop_index(op.f("ix_recurring_overrides_id"), table_name="recurring_overrides")
    op.drop_table("recurring_overrides")
    op.drop_index(op.f("ix_recurring_sessions_start_date"), table_name="recurring_sessions")
    op.drop_index(op.f("ix_recurring_sessions_id"), table_name="recurring_sessions")
    op.drop_table("recurring_sessions")
    op.drop_index(op.f("ix_one_time_sessions_start_date"), table_name="one_time_sessions")
    op.drop_index(op.f("ix_one_time_sessions_id"), table_name="one_time_sessions")
    op.drop_table("one_time_sessions")
    # ### end Alembic commands ###
